[[redirects]]
  from   = "https://nerdy.shermaineang.com/*"
  to     = "/nerdy/:splat"
  status = 200

[[redirects]]
  from   = "https://life.shermaineang.com/*"
  to     = "/life/:splat"
  status = 200
